# Codes - konfiguracja

# pl / en
language: en

# Czy przy starcie (i /code reload) nadpisywać messages_pl.yml wersją językową
# UWAGA: true nadpisze Twoje zmiany w messages_pl.yml
overwrite-messages: false

# LuckPerms
luckperms-integration: true

# Auto zapis co X minut
auto-save:
  enabled: true
  interval: 30